artifact_location: file:///Users/ganenthraravindran/Desktop/BIG%20DATA%20PROJECT/falabella-risk-engine/mlruns/148668678563615386
creation_time: 1776430027437
experiment_id: '148668678563615386'
last_update_time: 1776430027437
lifecycle_stage: active
name: falabella_baseline
