artifact_location: file:///Users/ganenthraravindran/Desktop/BIG%20DATA%20PROJECT/falabella-risk-engine/mlruns/750437185056794397
creation_time: 1776092928598
experiment_id: '750437185056794397'
last_update_time: 1776092928598
lifecycle_stage: active
name: falabella_baseline_smoke
