artifact_location: file:///Users/ganenthraravindran/Desktop/BIG%20DATA%20PROJECT/falabella-risk-engine/mlruns/0
creation_time: 1776092928593
experiment_id: '0'
last_update_time: 1776092928593
lifecycle_stage: active
name: Default
