artifact_location: file:///Users/ganenthraravindran/Desktop/BIG%20DATA%20PROJECT/falabella-risk-engine/mlruns/416453663268741833
creation_time: 1776092953758
experiment_id: '416453663268741833'
last_update_time: 1776092953758
lifecycle_stage: active
name: falabella_hybrid_smoke
